/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OUEC;

import Business.Complaint.Complaint;
import Business.EcoSystem;
import Business.Logic.OUEC.OUECCoordinator;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aamrah
 */
public class OUECCoordinatorJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form OUECCoordinatorJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    Complaint complaint, currentComplaint, mainComplaint;
    OUECCoordinator coord;
    ArrayList<OUECCoordinator> coordList;
    
    public OUECCoordinatorJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system)
    {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.system=system;
        coordList=this.system.getOuecCoordinators().getOuecCoordinatorList();
        for(OUECCoordinator c : coordList)
        {
            if(c.getEmployee().getUsername().equals(account.getUsername()))
            {
                coord=c;
            }
        }
        try{
            if(coord.getComplaint().getTypeOfComplaint().equals("Normal"))
            {
                CoordinatorNormalJPanel coordPanel= new CoordinatorNormalJPanel(userProcessContainer, account, system, complaint);
                userProcessContainer.add("Normal Complaint",coordPanel);
                CardLayout cardlayout= (CardLayout) userProcessContainer.getLayout();
                cardlayout.next(userProcessContainer);
            }
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(this, "You dont have any normal complaint assigned to you ");

        }
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStatus = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtComplaintID = new javax.swing.JTextField();
        txtVictimName = new javax.swing.JTextField();
        txtAccused = new javax.swing.JTextField();
        btnAcceptCase = new javax.swing.JButton();
        txtType = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblComplaintID = new javax.swing.JLabel();
        lblVIctimStudent = new javax.swing.JLabel();
        btnCaseClosed = new javax.swing.JButton();
        lblAccused = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnAddFeedback = new javax.swing.JButton();
        txtLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDF = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPF = new javax.swing.JTextArea();
        lblPF = new javax.swing.JLabel();
        lblDF = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        add(txtStatus);
        txtStatus.setBounds(520, 329, 205, 26);

        lblType.setText("Type of Incident");
        add(lblType);
        lblType.setBounds(348, 265, 102, 16);

        lblLocation.setText("Location:");
        add(lblLocation);
        lblLocation.setBounds(392, 307, 58, 16);
        add(txtComplaintID);
        txtComplaintID.setBounds(520, 169, 205, 26);

        txtVictimName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVictimNameActionPerformed(evt);
            }
        });
        add(txtVictimName);
        txtVictimName.setBounds(520, 201, 205, 26);

        txtAccused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccusedActionPerformed(evt);
            }
        });
        add(txtAccused);
        txtAccused.setBounds(520, 233, 205, 26);

        btnAcceptCase.setText("Accept Case");
        btnAcceptCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptCaseActionPerformed(evt);
            }
        });
        add(btnAcceptCase);
        btnAcceptCase.setBounds(244, 589, 121, 29);

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        add(txtType);
        txtType.setBounds(520, 265, 205, 26);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("STATUS CHANGES FOR COMPLAINTS");
        add(lblTitle);
        lblTitle.setBounds(0, 53, 1104, 56);

        lblComplaintID.setText("Complaint ID:");
        add(lblComplaintID);
        lblComplaintID.setBounds(363, 179, 87, 16);

        lblVIctimStudent.setText("Victim Name:");
        add(lblVIctimStudent);
        lblVIctimStudent.setBounds(366, 206, 84, 16);

        btnCaseClosed.setText("Case Closed");
        btnCaseClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaseClosedActionPerformed(evt);
            }
        });
        add(btnCaseClosed);
        btnCaseClosed.setBounds(719, 589, 121, 29);

        lblAccused.setText("Accused:");
        add(lblAccused);
        lblAccused.setBounds(393, 233, 57, 16);

        lblStatus.setText("Status:");
        add(lblStatus);
        lblStatus.setBounds(407, 334, 43, 16);

        btnAddFeedback.setText("Add Feedback");
        btnAddFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFeedbackActionPerformed(evt);
            }
        });
        add(btnAddFeedback);
        btnAddFeedback.setBounds(465, 589, 132, 29);
        add(txtLocation);
        txtLocation.setBounds(520, 297, 205, 26);

        txtDF.setColumns(20);
        txtDF.setRows(5);
        jScrollPane1.setViewportView(txtDF);

        add(jScrollPane1);
        jScrollPane1.setBounds(480, 463, 244, 84);

        txtPF.setColumns(20);
        txtPF.setRows(5);
        jScrollPane2.setViewportView(txtPF);

        add(jScrollPane2);
        jScrollPane2.setBounds(480, 361, 244, 84);

        lblPF.setText("Police Feedback");
        add(lblPF);
        lblPF.setBounds(350, 361, 100, 16);

        lblDF.setText("Driver Feedback");
        add(lblDF);
        lblDF.setBounds(348, 463, 101, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtVictimNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVictimNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVictimNameActionPerformed

    private void txtAccusedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccusedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccusedActionPerformed

    private void btnAcceptCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptCaseActionPerformed

        // change status to "Accepted Case"
        if(coord.getComplaint().getStatus().equalsIgnoreCase("New"))
        {
            
            currentComplaint=coord.getComplaint();
            currentComplaint.setStatus("Accepted");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "You already accepted the case \n Current Status :" + coord.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
    }//GEN-LAST:event_btnAcceptCaseActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void btnCaseClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaseClosedActionPerformed
        // TODO add your handling code here:
        if(coord.getComplaint().getStatus().equalsIgnoreCase("FeedbackAdded"))
        {
            
            
            currentComplaint.setStatus("TaskCompleted");
            mainComplaint.setStatus("CaseClosed"); 
            JOptionPane.showMessageDialog(this, "Task Completed, case closed");
            coord.setComplaint(null);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, " \n Current Status :" + coord.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
        
    }//GEN-LAST:event_btnCaseClosedActionPerformed

    private void btnAddFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFeedbackActionPerformed
        // TODO add your handling code here:
        if(coord.getComplaint().getStatus().equalsIgnoreCase("Accepted"))
        {
            
            currentComplaint=coord.getComplaint();
            currentComplaint.setStatus("FeedbackAdded");
            mainComplaint=system.getComplaintDirectory().getComplaint(currentComplaint.getComplaintID());
            mainComplaint.setOUECCoordinatorFeedback(JOptionPane.showInputDialog("What were your findings? "));

        }
        else
        {
            JOptionPane.showMessageDialog(null, " \n Current Status :" + coord.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
    }//GEN-LAST:event_btnAddFeedbackActionPerformed

    private void populateFields() 
    {
        if(coord.getComplaint()!= null)
        {
             complaint= coord.getComplaint();
             txtComplaintID.setText(complaint.getComplaintID());
             txtVictimName.setText(complaint.getVictimStudent().getName());
             txtAccused.setText(complaint.getAccusedStudent().getName());
             txtType.setText(complaint.getTypeOfIncident());
             txtLocation.setText(complaint.getLocation());
             txtStatus.setText(complaint.getStatus()); 
             txtPF.setText(complaint.getPoliceOfficerFeedback());
             txtDF.setText(complaint.getDriverFeedback());
             
        }
        else
        {
            JOptionPane.showMessageDialog(this,"You dont have any complaints assigned to you");
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptCase;
    private javax.swing.JButton btnAddFeedback;
    private javax.swing.JButton btnCaseClosed;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAccused;
    private javax.swing.JLabel lblComplaintID;
    private javax.swing.JLabel lblDF;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPF;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblVIctimStudent;
    private javax.swing.JTextField txtAccused;
    private javax.swing.JTextField txtComplaintID;
    private javax.swing.JTextArea txtDF;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextArea txtPF;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtVictimName;
    // End of variables declaration//GEN-END:variables
}
