/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OUEC;

import Business.Complaint.Complaint;
import Business.EcoSystem;
import Business.Logic.OUEC.OUECCoordinator;
import Business.Logic.OUEC.President;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aamrah
 */
public class PresidentJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form PresidentJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    ArrayList<Complaint> complaintDirectory;
    ArrayList<OUECCoordinator> coordinatorList;
   
    DefaultTableModel md;
    
    public PresidentJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) 
    {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.system=system;
        complaintDirectory=system.getComplaintDirectory().getComplaintList();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblComplaints = new javax.swing.JTable();
        lblHeading = new javax.swing.JLabel();
        lblCurrentStatus = new javax.swing.JLabel();
        btnPoliceOfficer = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        tblComplaints.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Complaint ID", "Priority", "Type of Incident", "Victim", "Accused", "Location", "Victim Contact", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblComplaints);

        lblHeading.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("All Complaints");

        lblCurrentStatus.setBackground(new java.awt.Color(255, 255, 255));
        lblCurrentStatus.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblCurrentStatus.setForeground(new java.awt.Color(255, 51, 51));

        btnPoliceOfficer.setBackground(new java.awt.Color(255, 51, 51));
        btnPoliceOfficer.setText("Assign OUEC Co-ordinator");
        btnPoliceOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliceOfficerActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 51, 51));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurrentStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPoliceOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(610, 610, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblHeading)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnPoliceOfficer)
                        .addGap(98, 98, 98)
                        .addComponent(lblCurrentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnRefresh)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPoliceOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliceOfficerActionPerformed
        // TODO add your handling code here:
        int selectedRow =tblComplaints.getSelectedRow();
            if (selectedRow < 0) {
                JOptionPane.showMessageDialog(null, "Please pick a complaint to assign to Coordinator!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                
                Complaint complaint= (Complaint) tblComplaints.getValueAt(selectedRow, 0);
                if(complaint.getStatus().equalsIgnoreCase("CaseClosed"))
                {
                    JOptionPane.showMessageDialog(null, "Case already closed, select another complaint to assign", "Warning", JOptionPane.WARNING_MESSAGE);

                }
                else
                {
            
                
                    CoordinatorAssignJPanel policePanel= new CoordinatorAssignJPanel(userProcessContainer, account, system, complaint);
                    userProcessContainer.add("AssignCoordinator",policePanel);
                    CardLayout cardlayout= (CardLayout) userProcessContainer.getLayout();
                    cardlayout.next(userProcessContainer);
                }
            }
            
           

    }//GEN-LAST:event_btnPoliceOfficerActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
       populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    public void populateTable()
    {
        try{
        md=(DefaultTableModel)tblComplaints.getModel();
        md.setRowCount(0);
        Object row[]= new Object[8];
        int i=0;
        for(Complaint c : complaintDirectory)
        {
            if(c.isOUEC())
            {
                    i=1;    
                    row[0]=c;
                    row[1]=c.getTypeOfComplaint();
                    row[2]=c.getTypeOfIncident();
                    row[3]=c.getVictimStudent().getName();
                    row[4]=c.getAccusedStudent().getName();
                    row[5]=c.getLocation();
                    row[6]=c.getVictimStudent().getPhone();
                    row[7]=c.getStatus();
                    md.addRow(row);
                
            }
           
            
                   
        }
        if(i==0)
        {
            JOptionPane.showMessageDialog(this,"No complaints for Office");
        }
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(this,"No complaints for Office");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPoliceOfficer;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentStatus;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JTable tblComplaints;
    // End of variables declaration//GEN-END:variables
}
