/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Signup;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Role.AdvisorRole;
import Business.Role.ChiefOfficerRole;
import Business.Role.DoctorRole;
import Business.Role.DriverRole;
import Business.Role.OUECCoordinatorRole;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Role.PoliceOfficerRole;
import Business.Role.PresidentRole;
import Business.Role.ReceptionistRole;
import Business.Role.StudentRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.util.regex.Pattern;
import java.awt.CardLayout;
import java.util.ArrayList;

/**
 *
 * @author Vignesh Gunasekaran <gunasekaran.v@northeastern.edu>
 */
public class EmployeeSignupJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system; 
    EnterpriseDirectory enterpriseDirectory;
    Enterprise NUPDEnterprise, OUECEnterprise, UHCSEnterprise, RedeyeEnterprise;

    /**
     * Creates new form EmployeeSignup
     */
    public EmployeeSignupJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        enterpriseDirectory=system.getEnterpriseDirectory();
//        if(enterpriseDirectory!=null)
        try{
            NUPDEnterprise=enterpriseDirectory.getEnterprise(Enterprise.EnterpriseType.NUPDEnterprise);
            OUECEnterprise=enterpriseDirectory.getEnterprise(Enterprise.EnterpriseType.OUECEnterprise);
            UHCSEnterprise=enterpriseDirectory.getEnterprise(Enterprise.EnterpriseType.UHCSEnterprise);
            RedeyeEnterprise=enterpriseDirectory.getEnterprise(Enterprise.EnterpriseType.RedeyeEnterprise);
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, " ED is empty");
        }
        
        
        String[] orgArray = {"--Select--", "NUPDEnterprise","OUECEnterprise", "RedeyeEnterprise", "UHCSEnterprise"};
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(orgArray);
        comboOrg1.setModel( model );
    }
    
//    private EmployeeSignupJPanel() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        closeJButton1 = new javax.swing.JButton();
        PasswordField1 = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nameJTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        uNameTextField1 = new javax.swing.JTextField();
        submitJButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        comboOrg1 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        comboRole1 = new javax.swing.JComboBox<>();
        txtEmail1 = new javax.swing.JTextField();
        txtneuid1 = new javax.swing.JTextField();
        txtPhone1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel17.setText("Password");
        add(jLabel17);
        jLabel17.setBounds(126, 170, 106, 16);

        closeJButton1.setText("Close");
        closeJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButton1ActionPerformed(evt);
            }
        });
        add(closeJButton1);
        closeJButton1.setBounds(960, 20, 79, 29);

        PasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField1ActionPerformed(evt);
            }
        });
        add(PasswordField1);
        PasswordField1.setBounds(350, 166, 144, 26);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Employee Signup");
        add(jLabel18);
        jLabel18.setBounds(243, 20, 152, 26);

        jLabel19.setText("Username");
        add(jLabel19);
        jLabel19.setBounds(126, 125, 62, 20);

        nameJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextField1ActionPerformed(evt);
            }
        });
        add(nameJTextField1);
        nameJTextField1.setBounds(350, 80, 144, 26);

        jLabel20.setText("Name");
        add(jLabel20);
        jLabel20.setBounds(126, 90, 36, 16);

        uNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameTextField1ActionPerformed(evt);
            }
        });
        add(uNameTextField1);
        uNameTextField1.setBounds(350, 122, 144, 26);

        submitJButton1.setText("Submit");
        submitJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButton1ActionPerformed(evt);
            }
        });
        add(submitJButton1);
        submitJButton1.setBounds(280, 540, 88, 29);

        jLabel21.setText("Email id");
        add(jLabel21);
        jLabel21.setBounds(129, 215, 103, 16);

        jLabel22.setText("NEU id");
        add(jLabel22);
        jLabel22.setBounds(129, 259, 42, 16);

        jLabel23.setText("Contact Number");
        add(jLabel23);
        jLabel23.setBounds(129, 303, 103, 16);

        comboOrg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboOrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrg1ActionPerformed(evt);
            }
        });
        add(comboOrg1);
        comboOrg1.setBounds(350, 340, 140, 27);

        jLabel24.setText("Organisation");
        add(jLabel24);
        jLabel24.setBounds(129, 346, 81, 16);

        jLabel25.setText("Role");
        add(jLabel25);
        jLabel25.setBounds(129, 391, 81, 16);

        comboRole1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRole1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRole1ActionPerformed(evt);
            }
        });
        add(comboRole1);
        comboRole1.setBounds(350, 390, 150, 27);

        txtEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail1ActionPerformed(evt);
            }
        });
        add(txtEmail1);
        txtEmail1.setBounds(350, 210, 144, 26);

        txtneuid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtneuid1ActionPerformed(evt);
            }
        });
        add(txtneuid1);
        txtneuid1.setBounds(350, 254, 144, 26);

        txtPhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhone1ActionPerformed(evt);
            }
        });
        add(txtPhone1);
        txtPhone1.setBounds(350, 298, 144, 26);

        jLabel26.setText("Only alphabets");
        add(jLabel26);
        jLabel26.setBounds(610, 80, 94, 16);

        jLabel27.setText("minimum length 5");
        add(jLabel27);
        jLabel27.setBounds(610, 120, 116, 16);

        jLabel28.setText("1 alphabet, 1 number, 1 !.*?");
        add(jLabel28);
        jLabel28.setBounds(610, 170, 173, 16);

        jLabel29.setText("exact 9 digits");
        add(jLabel29);
        jLabel29.setBounds(610, 260, 86, 16);

        jLabel30.setText("exact 10 digits");
        add(jLabel30);
        jLabel30.setBounds(610, 300, 94, 16);

        jLabel31.setText("Address");
        add(jLabel31);
        jLabel31.setBounds(129, 437, 81, 16);

        txtAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress1ActionPerformed(evt);
            }
        });
        add(txtAddress1);
        txtAddress1.setBounds(350, 440, 150, 26);

        jLabel32.setText("*All fields are mandatory");
        add(jLabel32);
        jLabel32.setBounds(270, 500, 156, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);
        
    }//GEN-LAST:event_closeJButton1ActionPerformed

    private void PasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField1ActionPerformed

    private void nameJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextField1ActionPerformed

    private void uNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameTextField1ActionPerformed

    private void submitJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButton1ActionPerformed
        // TODO add your handling code here:
        String name = nameJTextField1.getText();
        String uname=uNameTextField1.getText();
        String password=PasswordField1.getText();
        String email = txtEmail1.getText();
        String phone = txtPhone1.getText();
        String neuid = txtneuid1.getText();
        String address = txtAddress1.getText();
        String org = ("--Select--".equals(String.valueOf(comboOrg1.getSelectedItem())))? null : String.valueOf(comboOrg1.getSelectedItem());
        String role = ("--Select--".equals(String.valueOf(comboRole1.getSelectedItem())))? null : String.valueOf(comboRole1.getSelectedItem());

        try {
            if(name==null || name.length()<2 || Pattern.matches("^[A-Za-z]+(\\s[A-Za-z]+)*$", name)==false){
                throw new Exception("Name is mandatory and should be of pattern alphabets followed by space with alphabets");
            }
            if(uname==null || uname.length()<5){
                throw new Exception("Username is mandatory and is alphanumeric of minimum 5 lengths");
            }
            if (system.getUserAccountDirectory().checkIfUsernameIsUnique(uname)==false) {
                throw new Exception("User Name already exists");
            }
            if(password==null || Pattern.matches("^(?=(.*[a-z]){1,})(?=(.*[\\d]){1,})(?=(.*[\\W]){1,})(?!.*\\s).{5,30}$", password)==false){
                throw new Exception("Password is mandatory and of minimum 5 length with  atleast 1 alphabet, 1 number, 1 from ?!.*");
            }
            if(email==null || Pattern.matches("^([\\w\\.\\-]+)@([\\w\\-]+)((\\.(\\w){2,3})+)$", email)==false){
                throw new Exception("Email is mandatory and of minimum 5 length with  atleast 1 alphabet, 1 number, 1 from ?!.*");
            }
            if(phone==null || Pattern.matches("^\\d{10}$", phone)==false){
                throw new Exception("Phone is mandatory and of exact 10 numbers");
            }
            if(neuid==null || Pattern.matches("^\\d{9}$", neuid)==false){
                throw new Exception("Neuid is mandatory and of exact 9 numbers");
            }
            if(address==null || Pattern.matches("^[A-Za-z]+(\\s[A-Za-z]+)*$", address)==false){
                throw new Exception("Address is mandatory");
            }
            if (org==null) {
                JOptionPane.showMessageDialog(null,"Org is mandatory");
            }
            if (role==null) {
                JOptionPane.showMessageDialog(null,"Role is mandatory");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());

            return;
        } 
            //"PoliceOfficer","ChiefOfficer","OUECCoordinator","OUECInvestigator", "President","Driver","Doctor","Receptionist", "Advisor"
//              if ("PoliceOfficer".equals(role) )
//              {
//                  if(NUPDEnterprise!=null)
//                    {
//                        NUPDEnterprise.getOrganisationDirectory().getOrganisationList();
//                    }
//              }
           Employee e = system.getEmployeeDirectory().createEmployee(name, uname, password, address, phone, email, neuid);
           
           if ("PoliceOfficer".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new PoliceOfficerRole());
                system.getPoliceDirectory().createPoliceOfficer(name, uname, password, address, phone, email, neuid);
            } else if ("ChiefOfficer".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new ChiefOfficerRole());
                //no separate already in userAccount above line
            } else if ("OUECCoordinator".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new OUECCoordinatorRole());
                system.getOuecCoordinators().createOUECCoordinator(e);
            }  else if ("President".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new PresidentRole());
                //no separate already in userAccount above line
            }  else if ("Driver".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new DriverRole());
                system.getDriverDirectory().createDriver(e);
            } else if ("Doctor".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new DoctorRole());
                system.getDoctorDirectory().createDoctor(e);
            } else if ("Receptionist".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new ReceptionistRole());
                //no separate already in userAccount above line
            } else if ("Advisor".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new AdvisorRole());
                system.getAdvisorDirectory().createAdvisor(e);
            }

            JOptionPane.showMessageDialog(null,"You may now proceed to login!");

            nameJTextField1.setText("");
            uNameTextField1.setText("");
            PasswordField1.setText("");
            txtAddress1.setText("");
            txtPhone1.setText("");
            txtEmail1.setText("");
            txtneuid1.setText("");
        
    }//GEN-LAST:event_submitJButton1ActionPerformed

    private void comboOrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrg1ActionPerformed
        // TODO add your handling code here:
        String org = ("--Select--".equals(String.valueOf(comboOrg1.getSelectedItem())))? null : String.valueOf(comboOrg1.getSelectedItem());
        if (org!=null) {

            if ("NUPDEnterprise".equals(org)) {
                String[] roleArray = {"--Select--", "PoliceOfficer"};
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(roleArray);
                comboRole1.setModel( model );
            } else if ("OUECEnterprise".equals(org)) {
                String[] roleArray = {"--Select--", "OUECCoordinator"};
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(roleArray);
                comboRole1.setModel( model );
            } else if ("RedeyeEnterprise".equals(org)) {
                String[] roleArray = {"--Select--", "Driver"};
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(roleArray);
                comboRole1.setModel( model );
            } else if ("UHCSEnterprise".equals(org)) {
                String[] roleArray = {"--Select--", "Doctor", "Advisor"};
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(roleArray);
                comboRole1.setModel( model );
            }
        }
    }//GEN-LAST:event_comboOrg1ActionPerformed

    private void comboRole1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRole1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRole1ActionPerformed

    private void txtEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1ActionPerformed

    private void txtneuid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtneuid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtneuid1ActionPerformed

    private void txtPhone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhone1ActionPerformed

    private void txtAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JButton closeJButton1;
    private javax.swing.JComboBox<String> comboOrg1;
    private javax.swing.JComboBox<String> comboRole1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JButton submitJButton1;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtneuid1;
    private javax.swing.JTextField uNameTextField1;
    // End of variables declaration//GEN-END:variables
}
