/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Complaints;

import Business.Complaint.Complaint;
import Business.Complaint.ComplaintDirectory;
import Business.EcoSystem;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fianrodrigues
 */
public class EmergencyJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form EmergencyJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    ComplaintDirectory complaintDirectory;
    Complaint complaint;
    String typeOfIncident;
    Student victim, accused;
    
    public EmergencyJPanel(JPanel userProcessContainer, UserAccount account,EcoSystem system, Student victimStudent)
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account=account;
        this.victim=victimStudent;
        complaintDirectory =system.getComplaintDirectory();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        cmbTypeOfIncident1 = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMERGENCY COMPLAINT");
        add(jLabel1);
        jLabel1.setBounds(6, 50, 938, 56);

        jLabel2.setText("Location:");
        add(jLabel2);
        jLabel2.setBounds(326, 187, 117, 24);

        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        add(txtLocation);
        txtLocation.setBounds(449, 186, 184, 26);

        jLabel3.setText("Type:");
        add(jLabel3);
        jLabel3.setBounds(326, 234, 61, 16);

        btnSubmit.setBackground(new java.awt.Color(0, 153, 153));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(545, 349, 88, 29);

        cmbTypeOfIncident1.setBackground(new java.awt.Color(0, 153, 153));
        cmbTypeOfIncident1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Injury", "Sexual Assault", "Firearm", "Threats or Stalking" }));
        cmbTypeOfIncident1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeOfIncident1ActionPerformed(evt);
            }
        });
        add(cmbTypeOfIncident1);
        cmbTypeOfIncident1.setBounds(449, 230, 175, 27);

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setText("< Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(0, 15, 108, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MicrosoftTeams-image (1).png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(710, 20, 225, 230);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTypeOfIncident1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeOfIncident1ActionPerformed
        // TODO add your handling code here:

        String org = ("--Select--".equals(String.valueOf(cmbTypeOfIncident1.getSelectedItem())))? null : String.valueOf(cmbTypeOfIncident1.getSelectedItem());
        if (org!=null)
        {

            if ("Injury".equals(org))
            {
                typeOfIncident = "Injury";
            }
            else if ("Sexual Assault".equals(org))
            {
                typeOfIncident = "Sexual Assault";
            }
            else if ("Firearm".equals(org))
            {
                typeOfIncident = "Firearm";
            }
            else if ("Threats or Stalking".equals(org))
            {
                typeOfIncident = "Threats or Stalking";
            }
        }
    }//GEN-LAST:event_cmbTypeOfIncident1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        String location = txtLocation.getText();
        
        complaint = complaintDirectory.createComplaint("Emergency", victim, null, location, typeOfIncident);
        victim.getMyComplaints().add(complaint);
        JOptionPane.showMessageDialog(null, " Complaint registered with ID" +complaint.getComplaintID());
        clearTextFields();
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed
    public void clearTextFields()
    {
        txtLocation.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbTypeOfIncident1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
}
