/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NUPD;

import Business.Complaint.Complaint;
import Business.EcoSystem;
import Business.Logic.NUPD.PoliceOfficer;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fianrodrigues
 */
public class InjuryStatusJPanel extends javax.swing.JPanel
{

    /**
     * Creates new form InjuryStatusJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    Complaint complaint, currentComplaint, mainComplaint;
    PoliceOfficer police;
    public InjuryStatusJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, PoliceOfficer police,Complaint complaint)
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.complaint=complaint;
        this.police=police;
        police.setComplaint(complaint);
       currentComplaint=police.getComplaint();
        populateFields();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcceptCase = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnOnTheWay = new javax.swing.JButton();
        btnSceneReached = new javax.swing.JButton();
        btnDroppedOffAtUHCS = new javax.swing.JButton();
        btnTaskCompleted = new javax.swing.JButton();
        btnVictimPicked = new javax.swing.JButton();
        lblVictimStudent = new javax.swing.JLabel();
        lblAccusedStudent = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtComplaintID = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtVictimName = new javax.swing.JTextField();
        txtAccused = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        lblComplaintID = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnAcceptCase.setText("Accept Case");
        btnAcceptCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptCaseActionPerformed(evt);
            }
        });
        add(btnAcceptCase);
        btnAcceptCase.setBounds(197, 438, 121, 29);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("STATUS UPDATE FOR INJURY COMPLAINTS");
        add(lblTitle);
        lblTitle.setBounds(114, 53, 980, 56);

        btnOnTheWay.setText("On The Way");
        btnOnTheWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnTheWayActionPerformed(evt);
            }
        });
        add(btnOnTheWay);
        btnOnTheWay.setBounds(485, 438, 118, 29);

        btnSceneReached.setText("Scene Reached");
        btnSceneReached.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSceneReachedActionPerformed(evt);
            }
        });
        add(btnSceneReached);
        btnSceneReached.setBounds(776, 438, 136, 29);

        btnDroppedOffAtUHCS.setText("Dropped Off At UHCS");
        btnDroppedOffAtUHCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDroppedOffAtUHCSActionPerformed(evt);
            }
        });
        add(btnDroppedOffAtUHCS);
        btnDroppedOffAtUHCS.setBounds(611, 505, 179, 29);

        btnTaskCompleted.setText("Task Completed");
        btnTaskCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskCompletedActionPerformed(evt);
            }
        });
        add(btnTaskCompleted);
        btnTaskCompleted.setBounds(487, 614, 146, 29);

        btnVictimPicked.setText("Picked Up The Victim");
        btnVictimPicked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVictimPickedActionPerformed(evt);
            }
        });
        add(btnVictimPicked);
        btnVictimPicked.setBounds(310, 505, 177, 29);

        lblVictimStudent.setText("Victim Name:");
        add(lblVictimStudent);
        lblVictimStudent.setBounds(364, 208, 84, 16);

        lblAccusedStudent.setText("Accused:");
        add(lblAccusedStudent);
        lblAccusedStudent.setBounds(391, 235, 57, 16);

        lblStatus.setText("Status:");
        add(lblStatus);
        lblStatus.setBounds(405, 336, 43, 16);

        lblType.setText("Type:");
        add(lblType);
        lblType.setBounds(414, 267, 34, 16);
        add(txtLocation);
        txtLocation.setBounds(518, 299, 205, 26);
        add(txtComplaintID);
        txtComplaintID.setBounds(518, 171, 205, 26);

        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        add(txtStatus);
        txtStatus.setBounds(518, 331, 205, 26);

        txtVictimName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVictimNameActionPerformed(evt);
            }
        });
        add(txtVictimName);
        txtVictimName.setBounds(518, 203, 205, 26);

        txtAccused.setEnabled(false);
        txtAccused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccusedActionPerformed(evt);
            }
        });
        add(txtAccused);
        txtAccused.setBounds(518, 235, 205, 26);

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        add(txtType);
        txtType.setBounds(518, 267, 205, 26);

        lblLocation.setText("Location:");
        add(lblLocation);
        lblLocation.setBounds(390, 309, 58, 16);

        lblComplaintID.setText("Complaint ID:");
        add(lblComplaintID);
        lblComplaintID.setBounds(361, 181, 87, 16);

        btnBack.setText("< Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(0, 70, 108, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSceneReachedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSceneReachedActionPerformed
        // TODO add your handling code here:
        if(police.getComplaint().getStatus().equalsIgnoreCase("OnTheWay"))
        {
            
            currentComplaint=police.getComplaint();
            currentComplaint.setStatus("SceneReached");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " Current Status :" + police.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
    }//GEN-LAST:event_btnSceneReachedActionPerformed

    private void btnDroppedOffAtUHCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDroppedOffAtUHCSActionPerformed
        // TODO add your handling code here:
        
        // a pop up for the Police to write a description/feedback
        // change Status to new at Dropped off at UHCS
        if(police.getComplaint().getStatus().equalsIgnoreCase("VictimPicked"))
        {
            
            currentComplaint=police.getComplaint();
            currentComplaint.setStatus("DroppedToUHCS");
            currentComplaint.setUHCS(true);
            mainComplaint=system.getComplaintDirectory().getComplaint(currentComplaint.getComplaintID());
            mainComplaint.setUHCS(true);
            UserAccount receptionist = system.getUserAccountDirectory().fetchReceptionistFromUa();
            Complaint c = new Complaint(mainComplaint);
            c.setStatus("UHCS New");
            receptionist.getWorkQueue().getComplaintList().add(c);           
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, " Current Status :" + police.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
        
    }//GEN-LAST:event_btnDroppedOffAtUHCSActionPerformed

    private void btnOnTheWayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnTheWayActionPerformed
        // TODO add your handling code here:
        if(police.getComplaint().getStatus().equalsIgnoreCase("Accepted"))
        {
            
            currentComplaint=police.getComplaint();
            currentComplaint.setStatus("OnTheWay");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " Current Status :" + police.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
    }//GEN-LAST:event_btnOnTheWayActionPerformed

    private void btnTaskCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskCompletedActionPerformed
        // TODO add your handling code here:
        if(currentComplaint.getStatus().equals("DroppedToUHCS"))
        //if(mainComplaint.isUHCS() && mainComplaint.isReceptionistAccepted())
        {
            
            currentComplaint=police.getComplaint();
            currentComplaint.setStatus("TaskCompleted");
            
            //set complaint status in police complaint list as completed
            int i=police.getPoliceComplaints().indexOf(currentComplaint);
            police.getPoliceComplaints().get(i).setStatus("TaskCompleted");
            //set main complaint fields
            mainComplaint=system.getComplaintDirectory().getComplaint(currentComplaint.getComplaintID());
            mainComplaint.setPoliceOfficerFeedback(JOptionPane.showInputDialog("Enter your feedback for the case "));
            mainComplaint.setPolice(false);
            mainComplaint.setStatus("AssignedToUHCS");
            police.setComplaint(null);
        }
        else if(currentComplaint.getStatus().equals("TaskCompleted"))
        {
               JOptionPane.showMessageDialog(null, " You have already completed the task", "Warning", JOptionPane.WARNING_MESSAGE);
      
        }
        else 
        {
            JOptionPane.showMessageDialog(null, " Please make sure you have suspect in custody and chief is notified", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
    }//GEN-LAST:event_btnTaskCompletedActionPerformed

    private void btnVictimPickedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVictimPickedActionPerformed
        // TODO add your handling code here:
        if(police.getComplaint().getStatus().equalsIgnoreCase("SceneReached"))
        {
            
            currentComplaint=police.getComplaint();
            currentComplaint.setStatus("VictimPicked");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " Current Status :" + police.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
    }//GEN-LAST:event_btnVictimPickedActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtVictimNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVictimNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVictimNameActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void btnAcceptCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptCaseActionPerformed
        // TODO add your handling code here:
        if(police.getComplaint().getStatus().equalsIgnoreCase("New"))
        {
            
            currentComplaint=police.getComplaint();
            currentComplaint.setStatus("Accepted");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "You already accepted the case \n Current Status :" + police.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

          
           // JOptionPane.showMessageDialog(null, "You are already working on Complaint :"+police.getComplaint().getComplaintID() +"\n Current Status :" + police.getComplaint().getStatus()+"\nPlease finish task to proceed", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
        
    }//GEN-LAST:event_btnAcceptCaseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtAccusedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccusedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccusedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptCase;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDroppedOffAtUHCS;
    private javax.swing.JButton btnOnTheWay;
    private javax.swing.JButton btnSceneReached;
    private javax.swing.JButton btnTaskCompleted;
    private javax.swing.JButton btnVictimPicked;
    private javax.swing.JLabel lblAccusedStudent;
    private javax.swing.JLabel lblComplaintID;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblVictimStudent;
    private javax.swing.JTextField txtAccused;
    private javax.swing.JTextField txtComplaintID;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtVictimName;
    // End of variables declaration//GEN-END:variables

     private void populateFields() 
        {
        
             txtComplaintID.setText(complaint.getComplaintID());
             txtVictimName.setText(complaint.getVictimStudent().getName());
             txtType.setText(complaint.getTypeOfIncident());
             txtLocation.setText(complaint.getLocation());
             txtStatus.setText(complaint.getStatus());
        
             try
             {
                     txtAccused.setText(complaint.getAccusedStudent().getName());
             }
             catch (NullPointerException e)
             {
                 txtAccused.setText(" ");
             }
         }
}
