/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.UHCS;

import Business.Complaint.Complaint;
import Business.EcoSystem;
import Business.Logic.UHCS.Advisor;
import Business.Logic.UHCS.Doctor;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vignesh Gunasekaran <gunasekaran.v@northeastern.edu>
 */
public class AssignAdvisorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    Complaint complaintWorkRequest;
    EcoSystem system;
    
    /**
     * Creates new form AssignAdvisorJPanel
     */
    public AssignAdvisorJPanel(JPanel userProcessContainer, UserAccount account, Complaint complaintWorkRequest, EcoSystem system) {
         this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.complaintWorkRequest = complaintWorkRequest;
        this.system = system;
        initComponents();
        
        lblComplaintId.setText(complaintWorkRequest.getComplaintID());
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel md=(DefaultTableModel)tblAdvisorList.getModel();
        md.setRowCount(0);
        Object row[]= new Object[3];
        
        //taking network, enterprise level doctor list
            ArrayList<Advisor> advisorList  = system.getAdvisorDirectory().getAdvisorList();
        for (Advisor advisor : advisorList) {
            row[0] = advisor; //username gets printed
            row[1] = advisor.getEmployee().getName();
            row[2] = advisor.getEmployee().isIsFree();  //true false
                             
            md.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblComplaintId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdvisorList = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ASSIGN ADVISOR");

        jLabel2.setText("For the selected:");

        jLabel3.setText("Complaint ID:");

        tblAdvisorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Advisor UserName", "Advisor Name", "isFree?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAdvisorList);

        btnAssign.setBackground(new java.awt.Color(0, 153, 153));
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setText("< Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(lblComplaintId, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnAssign)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(lblComplaintId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnAssign)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        int selectedRow = tblAdvisorList.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select an advisor from the table to assign","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Advisor advisor  = (Advisor)tblAdvisorList.getValueAt(selectedRow, 0);
            boolean isFree = (boolean) tblAdvisorList.getValueAt(selectedRow, 2);
            
            if(!isFree) {
                JOptionPane.showMessageDialog(null,"Sorry selected advisor is not free, select another advisor who is free","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            //Set status of complaint
            complaintWorkRequest.setStatus("UHCS Advisor Assigned and Doctor Completed");
            
            //set AdvisorName on complaint
            //complaintWorkRequest.setAdvisor(advisor.getEmployee().getUsername());
            
            //assign it in enterprise level doctor object
            advisor.setComplaint(complaintWorkRequest);
            //advisor.getCompletedComplaintsList().add(complaintWorkRequest);
            //make doctor busy
            advisor.getEmployee().setIsFree(false);
            
            //assign it in userAccount level of doctor (to do on signup)
            UserAccount advisorUserAccount = system.getUserAccountDirectory().fetchUaWithUserName(advisor.getEmployee().getUsername());
            advisorUserAccount.getWorkQueue().getComplaintList().add(complaintWorkRequest);
            //make ua busy
            advisorUserAccount.getEmployee().setIsFree(false);
            
            JOptionPane.showMessageDialog(null,"Complaint with id: "+ complaintWorkRequest.getComplaintID() +"is assigned to Advisor "+advisor.getEmployee().getName());
                    
            // clear table
            DefaultTableModel model = (DefaultTableModel) tblAdvisorList.getModel();
            model.setRowCount(0);
        
            //back page
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);

        }

    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        // clear table
        DefaultTableModel model = (DefaultTableModel) tblAdvisorList.getModel();
        model.setRowCount(0);

        //back page
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComplaintId;
    private javax.swing.JTable tblAdvisorList;
    // End of variables declaration//GEN-END:variables
}
