/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.UHCS;

import Business.Complaint.Complaint;
import Business.EcoSystem;
import Business.Logic.UHCS.Doctor;
import Business.Logic.UHCS.DoctorDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vignesh Gunasekaran <gunasekaran.v@northeastern.edu>
 */
public class AssignDoctorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    Complaint complaintWorkRequest;
    EcoSystem system;
    
    /**
     * Creates new form AssignDoctorJPanel
     */
    public AssignDoctorJPanel(JPanel userProcessContainer, UserAccount account, Complaint complaintWorkRequest, EcoSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.complaintWorkRequest = complaintWorkRequest;
        this.system = system;
        initComponents();
        
        lblComplaintId.setText(complaintWorkRequest.getComplaintID());
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel md=(DefaultTableModel)tblDoctorList.getModel();
        md.setRowCount(0);
        Object row[]= new Object[3];
        
        //taking network, enterprise level doctor list
        ArrayList<Doctor> doctorList  = system.getDoctorDirectory().getDoctorList();
        for (Doctor doctor : doctorList) {
            row[0] = doctor; //username gets printed
            row[1] = doctor.getEmployee().getName();
            row[2] = doctor.getEmployee().isIsFree();  //true false
                             
            md.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssign = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctorList = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblComplaintId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnAssign.setBackground(new java.awt.Color(0, 153, 153));
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign);
        btnAssign.setBounds(600, 440, 87, 29);

        tblDoctorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor UserName", "Doctor Name", "isFree?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDoctorList);

        add(jScrollPane1);
        jScrollPane1.setBounds(220, 260, 454, 140);

        jLabel3.setText("Complaint ID:");
        add(jLabel3);
        jLabel3.setBounds(220, 210, 102, 16);
        add(lblComplaintId);
        lblComplaintId.setBounds(370, 210, 118, 22);

        jLabel2.setText("For the selected:");
        add(jLabel2);
        jLabel2.setBounds(220, 180, 104, 16);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ASSIGN DOCTOR");
        add(jLabel1);
        jLabel1.setBounds(0, 80, 990, 29);

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setText("< Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(0, 30, 103, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        int selectedRow = tblDoctorList.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a doctor from the table to assign","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Doctor doctor  = (Doctor)tblDoctorList.getValueAt(selectedRow, 0);
        boolean isFree = (boolean) tblDoctorList.getValueAt(selectedRow, 2);
            
            if(!isFree) {
                JOptionPane.showMessageDialog(null,"Sorry selected doctor is not free, select another doctor who is free","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //Set status of complaint 
            complaintWorkRequest.setStatus("UHCS Doctor Assigned");
            
            //set DoctorName on complaint
            //complaintWorkRequest.setDoctor(doctor.getEmployee().getUsername());
            
            //assign it in enterprise level doctor object
            doctor.setComplaint(complaintWorkRequest);
            //doctor.getCompletedComplaintsList().add(complaintWorkRequest);
            //make doctor busy
            doctor.getEmployee().setIsFree(false);
            
            //assign it in userAccount level of doctor (to do on signup)
            UserAccount doctorUserAccount = system.getUserAccountDirectory().fetchUaWithUserName(doctor.getEmployee().getUsername());
            doctorUserAccount.getWorkQueue().getComplaintList().add(complaintWorkRequest);
            //make ua busy
            doctorUserAccount.getEmployee().setIsFree(false);
            
            JOptionPane.showMessageDialog(null,"Complaint with id: "+ complaintWorkRequest.getComplaintID() +"is assigned to Doctor "+doctor.getEmployee().getName());
                    
            // clear table
            DefaultTableModel model = (DefaultTableModel) tblDoctorList.getModel();
            model.setRowCount(0);
        
            //back page
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);

        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        // clear table
        DefaultTableModel model = (DefaultTableModel) tblDoctorList.getModel();
        model.setRowCount(0);

        //back page
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComplaintId;
    private javax.swing.JTable tblDoctorList;
    // End of variables declaration//GEN-END:variables
}
