/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Redeye;

import Business.Complaint.Complaint;
import Business.EcoSystem;
import Business.Logic.Redeye.Driver;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fianrodrigues
 */
public class SexualAssaultRideStatusJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form SexualAssaultRideStatusJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    Complaint complaint, currentComplaint, mainComplaint;
    Driver driver;
 
    public SexualAssaultRideStatusJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, Driver driver, Complaint complaint) 
    {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.complaint=complaint;
        this.driver = driver;
        driver.setComplaint(complaint);
        populateFields();
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContact = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        txtComplaintID = new javax.swing.JTextField();
        txtVictimName = new javax.swing.JTextField();
        btnAcceptBooking = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblComplaintID = new javax.swing.JLabel();
        btnRideStarted = new javax.swing.JButton();
        lblVIctimStudent = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnSafelyDropped = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnOnPickupLocation = new javax.swing.JButton();

        setLayout(null);

        txtContact.setEditable(false);
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        add(txtContact);
        txtContact.setBounds(505, 265, 205, 26);

        lblLocation.setText("Location:");
        add(lblLocation);
        lblLocation.setBounds(370, 240, 58, 16);
        add(txtComplaintID);
        txtComplaintID.setBounds(505, 169, 205, 26);

        txtVictimName.setEditable(false);
        txtVictimName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVictimNameActionPerformed(evt);
            }
        });
        add(txtVictimName);
        txtVictimName.setBounds(505, 201, 205, 26);

        btnAcceptBooking.setText("Accept Booking");
        btnAcceptBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptBookingActionPerformed(evt);
            }
        });
        add(btnAcceptBooking);
        btnAcceptBooking.setBounds(180, 400, 142, 29);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("RIDE STATUS FOR SEXUAL ASSAULT CASES");
        add(lblTitle);
        lblTitle.setBounds(0, 50, 1096, 56);

        lblComplaintID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblComplaintID.setText("Ride ID:");
        add(lblComplaintID);
        lblComplaintID.setBounds(370, 180, 49, 16);

        btnRideStarted.setText("Ride Started");
        btnRideStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRideStartedActionPerformed(evt);
            }
        });
        add(btnRideStarted);
        btnRideStarted.setBounds(530, 400, 119, 29);

        lblVIctimStudent.setText("Victim Name:");
        add(lblVIctimStudent);
        lblVIctimStudent.setBounds(340, 210, 84, 16);

        lblContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblContact.setText("Contact:");
        add(lblContact);
        lblContact.setBounds(360, 270, 70, 16);

        txtLocation.setEditable(false);
        add(txtLocation);
        txtLocation.setBounds(505, 233, 205, 26);

        btnSafelyDropped.setText("Safely Dropped");
        btnSafelyDropped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSafelyDroppedActionPerformed(evt);
            }
        });
        add(btnSafelyDropped);
        btnSafelyDropped.setBounds(720, 400, 139, 29);

        txtStatus.setEditable(false);
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        add(txtStatus);
        txtStatus.setBounds(510, 300, 205, 26);

        lblStatus.setText("Status:");
        add(lblStatus);
        lblStatus.setBounds(380, 300, 43, 16);

        btnOnPickupLocation.setText("At Pickup Location");
        btnOnPickupLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnPickupLocationActionPerformed(evt);
            }
        });
        add(btnOnPickupLocation);
        btnOnPickupLocation.setBounds(350, 400, 162, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtVictimNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVictimNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVictimNameActionPerformed

    private void btnAcceptBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptBookingActionPerformed

        // change status to "Accepted Case"
        if(driver.getComplaint().getStatus().equalsIgnoreCase("NewRide"))
        {
            
            currentComplaint=driver.getComplaint();
            currentComplaint.setStatus("Accepted");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "You already accepted the ride \n Current Status :" + driver.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
    }//GEN-LAST:event_btnAcceptBookingActionPerformed

    private void btnRideStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRideStartedActionPerformed
        // TODO add your handling code here:
        if(driver.getComplaint().getStatus().equalsIgnoreCase("At PickUp location"))
        {
            
            currentComplaint=driver.getComplaint();
            currentComplaint.setStatus("Ride Started");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " Current Status :" + driver.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();
    }//GEN-LAST:event_btnRideStartedActionPerformed

    private void btnSafelyDroppedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSafelyDroppedActionPerformed
        // TODO add your handling code here:
            currentComplaint=driver.getComplaint();
            currentComplaint.setStatus("DroppedToUHCS");
            currentComplaint.setUHCS(true);
            mainComplaint=system.getComplaintDirectory().getComplaint(currentComplaint.getComplaintID());
            mainComplaint.setDriverFeedback(JOptionPane.showInputDialog("How was the passenger's condition? "));
            mainComplaint.setUHCS(true);
            driver.setComplaint(null);
            UserAccount receptionist = system.getUserAccountDirectory().fetchReceptionistFromUa();
            Complaint c = new Complaint(mainComplaint);
            c.setStatus("UHCS New");
            receptionist.getWorkQueue().getComplaintList().add(c); 
    }//GEN-LAST:event_btnSafelyDroppedActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void btnOnPickupLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnPickupLocationActionPerformed

        // change status to "Accepted Case"
        if(driver.getComplaint().getStatus().equalsIgnoreCase("Accepted"))
        {

            currentComplaint=driver.getComplaint();
            currentComplaint.setStatus("At PickUp location");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " Current Status :" + driver.getComplaint().getStatus()+"\nPlease go to next step", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateFields();

    }//GEN-LAST:event_btnOnPickupLocationActionPerformed
    private void populateFields() 
    {
             txtComplaintID.setText(complaint.getComplaintID());
             txtVictimName.setText(complaint.getVictimStudent().getName());
             txtContact.setText(complaint.getVictimStudent().getPhone());
             txtLocation.setText(complaint.getLocation());
             txtStatus.setText(complaint.getStatus());       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptBooking;
    private javax.swing.JButton btnOnPickupLocation;
    private javax.swing.JButton btnRideStarted;
    private javax.swing.JButton btnSafelyDropped;
    private javax.swing.JLabel lblComplaintID;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVIctimStudent;
    private javax.swing.JTextField txtComplaintID;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtVictimName;
    // End of variables declaration//GEN-END:variables


}
